//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2019.12.15 at 02:01:33 PM IST 
//

package com.jercey.ws.valObj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
* <p>Java class for anonymous complex type.
* 
* <p>The following schema fragment specifies the expected content contained within this class.
* 
* <pre>
* &lt;complexType>
*   &lt;complexContent>
*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
*       &lt;sequence>
*         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="RequestType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
*         &lt;element name="FileKeys" type="{}valuelist"/>
*       &lt;/sequence>
*     &lt;/restriction>
*   &lt;/complexContent>
* &lt;/complexType>
* </pre>
* 
* 
*/
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
 "firstName",
 "lastName",
 "requestType",
 "fileKeys"
})
@XmlRootElement(name = "Author")
public class Author {

 @XmlElement(name = "FirstName")
 protected String firstName;
 @XmlElement(name = "LastName")
 protected String lastName;
 @XmlElement(name = "RequestType")
 protected String requestType;
 @XmlList
 @XmlElement(name = "FileKeys", required = true)
 protected List<String> fileKeys;

 /**
  * Gets the value of the firstName property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getFirstName() {
     return firstName;
 }

 /**
  * Sets the value of the firstName property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setFirstName(String value) {
     this.firstName = value;
 }

 /**
  * Gets the value of the lastName property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getLastName() {
     return lastName;
 }

 /**
  * Sets the value of the lastName property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setLastName(String value) {
     this.lastName = value;
 }

 /**
  * Gets the value of the requestType property.
  * 
  * @return
  *     possible object is
  *     {@link String }
  *     
  */
 public String getRequestType() {
     return requestType;
 }

 /**
  * Sets the value of the requestType property.
  * 
  * @param value
  *     allowed object is
  *     {@link String }
  *     
  */
 public void setRequestType(String value) {
     this.requestType = value;
 }

 /**
  * Gets the value of the fileKeys property.
  * 
  * <p>
  * This accessor method returns a reference to the live list,
  * not a snapshot. Therefore any modification you make to the
  * returned list will be present inside the JAXB object.
  * This is why there is not a <CODE>set</CODE> method for the fileKeys property.
  * 
  * <p>
  * For example, to add a new item, do as follows:
  * <pre>
  *    getFileKeys().add(newItem);
  * </pre>
  * 
  * 
  * <p>
  * Objects of the following type(s) are allowed in the list
  * {@link String }
  * 
  * 
  */
 public List<String> getFileKeys() {
     if (fileKeys == null) {
         fileKeys = new ArrayList<String>();
     }
     return this.fileKeys;
 }

}
